//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaCelulares.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Call_Detail
    {
        public int Id_Call_Detail { get; set; }
        public string CallDetailId { get; set; }
        public int Id_Mobile_Line { get; set; }
        public string MobileLine { get; set; }
        public string CalledPartyNumber { get; set; }
        public string CalledPartyDescription { get; set; }
        public System.DateTime DateTime { get; set; }
        public int Duration { get; set; }
        public decimal TotalCost { get; set; }
    
        public virtual Mobile_Line Mobile_Line { get; set; }
    }
}
